2024-02-09 04:28:26,433 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddf79fc0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:28:27,460 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0deb31540>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:28:27,993 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd677220>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:28:29,611 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd675630>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:28:30,719 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd676350>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:28:30,756 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd674f40>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:28:30,758 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6f17e0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:28:38,763 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddf78910>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:29:29,788 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddfc26e0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:29:41,983 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6abee0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:29:43,102 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6a92d0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:29:44,139 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32da50>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:29:44,169 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32c910>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:29:44,193 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6a91e0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:29:46,051 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddfc10f0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:29:48,709 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddfc06d0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:11,942 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6aa7d0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:13,085 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0ddfc16c0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:13,109 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd6f18d0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:47,723 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd677d60>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:49,001 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd676620>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:50,043 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dfa6a830>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:51,200 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0deb30af0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:52,275 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32c400>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:30:54,515 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df32ffd0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:01,872 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df3811e0>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:03,068 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0df383670>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:04,102 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd676350>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
2024-02-09 04:31:04,117 ERROR: Elasticsearch indexing error: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fd0dd677610>: Failed to establish a new connection: [Errno 111] Connection refused)) [in /home/egoza/PycharmProjects/LUDAPROJECT/app/search.py:14]
